---
title: "Reto2"
author: "Blockchain Patrol"
date: "2023-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Crypto Datathon Reto 1

```{r message= FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(readr)
library(ggplot2)
library(PerformanceAnalytics)
library(dygraphs)
library(tidyr)
library(cluster)
library(NbClust)
library(fpc) 
library(factoextra)
library(corrplot)
```


Cargamos en primer lugar la información cualitativa de las monedas.

```{r message= FALSE, warning=FALSE}

info_cualitativa <- read_csv2('./Data/informacion_cualitativa_monedas_reto2.csv', show_col_types = FALSE)
str(info_cualitativa)

```

Ahora cargamos la información cuantitativa de monedas en un único dataset

```{r message= FALSE, warning=FALSE}

info_cuantitativa <-
  list.files(path = 'Data/información_cuantitava_monedas_reto2', pattern = "*.csv", full.names = TRUE, recursive = TRUE) %>%
  map_df(~fread(.x))

str(info_cuantitativa)

```

Vamos a ver la relación de BTC/USD

```{r}
colnames(info_cuantitativa) <- c("Hora", "Exchange","Divisa", "Datos")
infoBTCUSD<-info_cuantitativa[info_cuantitativa$Divisa == 'BTC/USDT']
```

Necesitaríamos de la columna "Datos", crear una columna con los bids y otra con los asks

```{r}

library(purrr)
library(jsonlite)
info_cuantitativa_json <- jsonlite::stream_in(textConnection(gsub("\\n", "", gsub("'", "\"", gsub("None", "\"0\"", info_cuantitativa$Datos)))))

#info_cuantitativa_json <- as.data.frame(do.call(cbind, info_cuantitativa_json))

df_bids <- info_cuantitativa_json[, c(1, 2, 4, 5, 6)] %>%
  unnest(bids)
df_asks <- info_cuantitativa_json[, c(1, 3, 4, 5, 6)] %>%
  unnest(asks)

```

```{r}

df <- jsonlite::stream_in(textConnection(gsub("\\n", "", info_cuantitativa$Datos)))


library(jsonlite)
# single quote is invalid, so if real, you need to replace them all by double quote
info_cuantitativa$Datos <- gsub("'", "\"", info_cuantitativa$Datos)
info_cuantitativa$Datos <- gsub("None", "\"0\"", info_cuantitativa$Datos)
# parse the json
info_cuatitativa_json <- fromJSON(info_cuantitativa$Datos)

```